// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"
)

type Account struct {
	ID        int64     `json:"id"`
	Owner     int64     `json:"owner"`
	Balance   int64     `json:"balance"`
	Currency  string    `json:"currency"`
	CreatedAt time.Time `json:"created_at"`
}

type Entry struct {
	ID        int64     `json:"id"`
	Amount    int64     `json:"amount"`
	AccountID int64     `json:"account_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Transfar struct {
	ID int64 `json:"id"`
	// Must be positive
	Amount        int64     `json:"amount"`
	Status        string    `json:"status"`
	FromAccountID int64     `json:"from_account_id"`
	ToAccountID   int64     `json:"to_account_id"`
	CreatedAt     time.Time `json:"created_at"`
}

type User struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"created_at"`
}
