name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Install migrate CLI
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz \
          | tar xvz
          sudo mv migrate /usr/local/bin

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U root; do
            echo "Waiting for postgres..."
            sleep 2
          done

      - name: Create simple_bank database
        run: psql -h localhost -U root -c "CREATE DATABASE simple_bank;" postgres
        env:
          PGPASSWORD: password

      - name: Run migrations
        run: make migrate_up
        env:
          PG_USER: root
          PG_PASSWORD: password
          PG_PORT: 5432
          PG_DB: simple_bank

      - name: Test
        run: make test
        env:
          PG_USER: root
          PG_PASSWORD: password
          PG_PORT: 5432
          PG_DB: simple_bank
